services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: src/backend/core/db/Dockerfile
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpwd
      POSTGRES_DB: testdb
    ports:
      - 127.0.0.1:5432:5432
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    depends_on:
      - db
    ports:
      - 127.0.0.1:3000:3000
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    depends_on:
      - backend
      - db
    ports:
      - 127.0.0.1:1234:1234